export enum LogAction {
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",

  CREATE_CATEGORY = "CREATE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",

  CREATE_MEDICINE = "CREATE_MEDICINE",
  UPDATE_MEDICINE = "UPDATE_MEDICINE",
  DELETE_MEDICINE = "DELETE_MEDICINE",

  CREATE_RECORD = "CREATE_RECORD",
  UPDATE_RECORD = "UPDATE_RECORD",
  DELETE_RECORD = "DELETE_RECORD",

  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
}
